# Generated by Django 3.1.2 on 2020-10-05 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('category_img', models.ImageField(upload_to='imagesDB')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.categorylink')),
            ],
            options={
                'verbose_name': 'Category of links',
                'verbose_name_plural': 'Categories of links',
            },
        ),
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=20)),
                ('link_logo', models.ImageField(upload_to='imagesDB')),
                ('link_domain', models.CharField(max_length=20)),
                ('visited_people_number_on_last_month', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField()),
                ('link_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.categorylink')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='VisitedHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.linkmodel')),
            ],
            options={
                'verbose_name': 'Visited link',
                'verbose_name_plural': 'Visited links',
            },
        ),
        migrations.CreateModel(
            name='LinksInWishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('session_key', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.linkmodel')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link in wishlist',
                'verbose_name_plural': 'Links in wishlist',
            },
        ),
    ]
