# Generated by Django 3.1.2 on 2020-10-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylink',
            name='category_name_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categorylink',
            name='category_name_kk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categorylink',
            name='category_name_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='linkmodel',
            name='link_title_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='linkmodel',
            name='link_title_kk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='linkmodel',
            name='link_title_ru',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
