# Generated by Django 3.1.2 on 2020-10-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_auto_20201013_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylink',
            name='country',
            field=models.CharField(choices=[('KZ', 'KAZAKHSTAN'), ('World', 'WORLD')], max_length=300, null=True),
        ),
    ]
