# Generated by Django 3.1.2 on 2020-10-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_categorylink_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorylink',
            name='country',
        ),
        migrations.AddField(
            model_name='linkmodel',
            name='country',
            field=models.CharField(choices=[('KZ', 'KAZAKHSTAN'), ('World', 'WORLD')], max_length=300, null=True),
        ),
    ]
