# Generated by Django 3.1.2 on 2020-10-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_auto_20201013_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylink',
            name='category_img',
            field=models.ImageField(null=True, upload_to='imagesDB'),
        ),
    ]
