# Generated by Django 3.1.2 on 2020-10-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_auto_20201013_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylink',
            name='category_img',
            field=models.ImageField(blank=True, null=True, upload_to='imagesDB'),
        ),
        migrations.AlterField(
            model_name='categorylink',
            name='category_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='categorylink',
            name='category_name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='categorylink',
            name='category_name_kk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='categorylink',
            name='category_name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
