# Generated by Django 3.1.2 on 2020-10-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0007_auto_20201013_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylink',
            name='category_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='categorylink',
            name='category_name_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='categorylink',
            name='category_name_kk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='categorylink',
            name='category_name_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='link_title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='link_title_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='link_title_kk',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='link_title_ru',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
